### ISSUE TITLE
UpdateAction method gets called multiple times when Plugin Manager is opened multiple times

### ISSUE THREAD

**Issue by andrewisplinghoff** [VIISON/shopware-4#12]
To reproduce: open the plugin manager multiple times. Quickly pressing CTRL+ALT+P multiple times will do. Then click an "Update" icon of some plugin. The updateAction will get called multiple times, making the update quite likely fail because it gets performed two or more times in parallel.

![selection_646](https://cloud.githubusercontent.com/assets/105166/11939800/c6e5895c-a824-11e5-8899-effd40e49c32.png)

**Comment by samuelvogel** [comment]
Isn't the plugin manager actually a singleton? So this is more a race condition while opening it and will probably not be encountered by regular users?!

**Comment by andrewisplinghoff** [comment]
Yes, the plugin manager has been changed to automatically make sure that only one instance of the dialog is open in Shopware 5: https://github.com/VIISON/shopware/commit/6e31ce2ff66d1e2b95e3f41b56b6c8837cfab494

I'll close the issue since the discussed problem cannot occur anymore in current Shopware versions.
