### ISSUE TITLE
Clear doctrine metadata cache before plugin update

### ISSUE THREAD

**Issue by samuelvogel** [VIISON/shopware-4#19]
The [method](https://github.com/shopware/shopware/blob/27507fe404cede0b75ad561fc081ce4fc9554569/engine/Shopware/Components/CacheManager.php#L209-L212) to clear the doctrine metadata cache needs to be executed before each plugin update. Otherwise schema changes might not be taken into account when `update()` is run.

**Comment by svenmuennich** [comment]
I modified ShopwareCommon's `update` method to clear the proxy cache, which includes clearing the metadata. Since all our plugins (should) call the parent `update` method first, a ShopwareCommon upgrade to at least `v2.67.0` fixes this issue.
