### ISSUE TITLE
Fix basket price calculation

### ISSUE THREAD

**Issue by stefanheppenheimer** [VIISON/shopware-4#23]
One of our customers discovered a price calculation bug in Shopware's basket module. This bug is reproduceable and occurs, when a customer, which is exempted from vat (taxfree), adds an article to the basket. Depending on the configuration of the article this may end up with a new basket item, whose net price is greater than its gross price, which in turn leads to wrong total amount in case that the customer orders the article. We should fix this bug and send Shopware a suitable PR.

To prepare and streamline this process I've already created a new branch "fix-basket-price-calculation" and added a test case, which reproduces the bug.

**Comment by samuelvogel** [comment]
We submitted the fix for this as a PR almost two years ago already: https://github.com/shopware/shopware/pull/217

But that was without a test case, so I just updated the [current PR](https://github.com/shopware/shopware/pull/556) with the test case you provided.
