### ISSUE TITLE
Document creation for inactive subshops

### ISSUE THREAD

**Issue by antoniokupresak** [VIISON/shopware-4#24]
When trying to create a document for inactive subshops (e.g. a POS subshop), you get a generic 503 error. 

Turning the shopware logging on shows a null error (`Call to a member function setCurrency() on null)` in this line https://github.com/shopware/shopware/blob/fb9704a63802e2bc16bb68c6615b478202998ca6/engine/Shopware/Components/Document.php#L533

We should either show a better error message here or allow creating documents for subshops via a pr

**Comment by samuelvogel** [comment]
Since this problem reoccured this week (Arbeitsschützer _15e0f6681af72e6d_, _15e0a273f4ed9168_, _15e096be1fd0dd94_ & _15df4a03f885ebfa_) I finally created a (pretty trivial) Shopware PR for this: https://github.com/shopware/shopware/pull/1248
