### ISSUE TITLE
[PR] Add base store for 'document type's

### ISSUE THREAD

**Issue by svenmuennich** [VIISON/shopware-4#34]
Currently it is not possible to add a config element to plugin config forms for selecting document types, e.g. _invoice_, _deliver notes_ etc. Therefore we have to add a base store for this.

Once the PR is merged, we should add a gate to the ViisonPickwareMobile app based on the Shopware version, to allow selecting the extra document types instead of entering their IDs (see VIISON/PickingApp#152).

**Comment by fixpunkt** [comment]
Impl'd in https://github.com/shopware/shopware/pull/1120.
