### ISSUE TITLE
[PR] Recalculate order invoice amount after adding position 

### ISSUE THREAD

**Issue by yannickschmidt** [VIISON/shopware-4#44]
When the costumer chooses "cash on delivery" as payment and the shop owner adds a position for that order afterwards. The invoice amount says the same (see screenshot). This leads to the bug, that we don't print the correct amount on the shipping label and the costumer doesn't pay the full price.

Funny is, that the amount gets recalculated correctly, when deleting a position.

![invoice amount after adding a position](https://user-images.githubusercontent.com/26897504/30429527-26a2b182-9958-11e7-91a2-6258adccf1ce.png)

**Comment by antoniokupresak** [comment]
It turns out that this is not a general shopware bug...
