### ISSUE TITLE
Allow optional creation of multiple documents per order with the same type

### ISSUE THREAD

**Issue by samuelvogel** [VIISON/shopware-4#53]
Shopware currently only allows one document per type for an order, which is enforced here:
https://github.com/VIISON/shopware/blob/709dbfc765dafa0dcc6c1b29f2efad4e58a08b80/engine/Shopware/Components/Document.php#L578-L583

There should be an optional parameter which allows to skip this check.

**Comment by hanneswernery** [comment]
[PR](https://github.com/shopware/shopware/pull/1380) pending.
