### ISSUE TITLE
Disallow overwriting changed orders with an older version

### ISSUE THREAD

**Issue by samuelvogel** [VIISON/shopware-4#61]
Somewhat similar to #39 for articles, we want to prevent customer orders from being overwritten in the backend while or after they have been picked. This happens when the order is opened in the backend while changes are made via the API and the order is then saved afterwards. In the ExtJS backend the old state of the order (with the changes made by the user) will be written to the database, disregarding and overwriting any other changes which happened while the order was open in the backend.

As most changes to an order are pretty small (changing a status or adding a position) they can easily be redone. Therefore we can just block them with an appropriate message when the order is in a different state then when it was opened in the backend.

The state should probably be a timestamp column which should be updated via doctrine (watch out for attached entities like order details).

**Comment by windaishi** [comment]
I made a PR about this concern: https://github.com/shopware/shopware/pull/1468

**Comment by windaishi** [comment]
Since the PR in Shopware is closed i created a new internal one:
https://github.com/VIISON/shopware/pull/63

Additionally I created a Monkey Patch for ERP that does the same:
--redacted--

They both need a review.

**Comment by fixpunkt** [comment]
New, scheduled Shopware PR here: https://github.com/shopware/shopware/pull/1474

**Comment by fixpunkt** [comment]
Hotfix released in ERP v4.0.7-4.0.9.

**Comment by fixpunkt** [comment]
We should check whether this fixes #39 too.

**Comment by windaishi** [comment]
It doesn'T
