### ISSUE TITLE
Include articleDetailId in order detail model

### ISSUE THREAD

**Issue by antoniokupresak** [VIISON/shopware-4#69]
There is currently no link between an order detail and the articleDetailId (i.e. an article variant) besides the `articleordernumber`. However, this is useless since both, the `articleordernumber` in `s_order_details` and the `ordernumber` in `s_articles_details` are mutable by the user. 

This breaks nearly every process in Pickware if one of the numbers are changed.

We should therefore open a shopware PR to include the articleDetailId in the order detail model.

**Comment by windaishi** [comment]
I opened the PR https://github.com/shopware/shopware/pull/1632 in the SW repository. I prioritized it as High in our PR list
