### ISSUE TITLE
Corrupted mail templates result in stock errors when saving order status via order list or order detail window

### ISSUE THREAD

**Issue by windaishi** [VIISON/shopware-4#70]
When there are errors in mail templates, for example Smarty syntax error, this error loads to several crashes durching processes that are relevant for stock managing. Therefore Corrupted mail templates can lead to stock errors. 
This is the case when changing status for one ordervia the order detail window or the order list.
There should be a PR which swallows the mail error and therefore archive that the afterhooks are still executed. 
See this issue for more infos: https://github.com/VIISON/ShopwarePickwareERP/issues/658#issuecomment-373452295

**Comment by windaishi** [comment]
Review PR in our SW repo: https://github.com/VIISON/shopware/pull/76

**Comment by samuelvogel** [comment]
We opened https://github.com/shopware/shopware/pull/1496 for this.
