### ISSUE TITLE
Internal review for "Add articleDetailId to s_order_details" SW#1632

### ISSUE THREAD

**Issue by cjuner** [VIISON/shopware-4#77]
https://github.com/shopware/shopware/pull/1632 is still missing an internal review.

**Comment by cjuner** [comment]
@windaishi, if one exists, please refer to the original issue here.

Also, see https://github.com/VIISON/shopware/issues/73 as a tracking issue.

**Comment by windaishi** [comment]
https://github.com/VIISON/shopware/issues/69

**Comment by cjuner** [comment]
@windaishi, thanks. I wasn't aware of the issue, glad to see it's already in review :)

This one is redundant, then. Closing in favor of https://github.com/VIISON/shopware/issues/69.
