### ISSUE TITLE
[PR]Change data type of s_order.trackingcode

### ISSUE THREAD

**Issue by philippseemann** [VIISON/shopware-4#82]
### How can the enhancement be summarized in two to three sentences?
Right now the attribute is limited to 255 characters. This leads to the problem that only 9 shipping labels can be created. By changing the data type and the maximum length it'll be possible to generate more than 9 shipping labels.
### How does the system behave currently (before applying the enhancement)?
Right now the data type is varchar(255)
### How should the system behave once the enhancement is implemented?
We should change the data type to text with a bigger limitation.
### How could this be implemented?
Change the datatype with a shopware PR
### Who is affected by this issue and who is involved?
https://basecamp.com/1905570/projects/2934650/todos/306051554
### What action items are left to be done on this issue?
Make the PR.

**Comment by niklasbuechner** [comment]
PR ready to review: https://github.com/VIISON/shopware-private/pull/2

**Comment by niklasbuechner** [comment]
The pr has been merged, but not yet released.
