### ISSUE TITLE
[PR] Workaround for non-null default dates on MariaDB

### ISSUE THREAD

**Issue by fixpunkt** [VIISON/shopware-4#83]
We've just seen another case which seems related to https://github.com/shopware/shopware/pull/1396. The difference is that there's a `DATE` column with an actual non-null default where the default in `information_schema.COLUMNS` is enclosed in single-quotes as opposed to no quotes for proper MySQL.

This causes this attribute constructor code to be generated for `\Shopware\Models\Attribute\Order`:

```php
public function __construct()
{
    $this->viisonLastChanged = new \DateTime("'2000-01-01 00:00:00'");
    $this->viisonPosTransactionType = "'order'";
}
```

This causes the `\DateTime` constructor to throw an exception. The customer was on `10.2.17-MariaDB-10.2.17+maria~stretch`. We need to check whether this issue is also present in MariaDB 10.2.7, which was the version which introduced the previous bug.

We need to make another PR which works around this MariaDB compatibility problem (or convince everyone to drop MariaDB support...).

**Comment by shyim** [comment]
Already fixed https://github.com/shopware/shopware/commit/f58a0d9136adcb1178280bdf6ea9f38f7904aa01

**Comment by fixpunkt** [comment]
Awesome, and thanks for letting us know!
